version: '3.7'

services:

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    network_mode: host

  worker:
    build: ./project
    command: celery -A cafe.background.app:celery worker --loglevel=info
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
