"""init

Revision ID: 0.0.1
Revises: 
Create Date: 2022-03-04 19:06:01.542802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0.0.1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'burgers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('price', sa.DECIMAL(precision=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cost', sa.DECIMAL(precision=2), nullable=False),
        sa.Column('state', sa.Enum('new', 'prepared', 'completed', name='orderstate'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'orders_positions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('burger_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['burger_id'],
            ['burgers.id'],
        ),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_positions')
    op.drop_table('orders')
    op.drop_table('burgers')
    # ### end Alembic commands ###
